version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      [
        "./wait-for-it.sh",
        "dbpg:3456",
        "--",
        "python",
        "app.py"
      ]
    depends_on:
      - dbpg
    volumes:
      - "./app/.:/app"
    ports:
      - "80:5000"

  # db:
  #   image: mysql:8.0.21
  #   ports:
  #     - "33060:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: WG?E){C3>Qnvcwe+
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/:ro

  dbpg:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "34560:3456"
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
    driver: local
