version: "3"
services:
  apiv1:
    build:
      context: ./apiv1
      dockerfile: Dockerfile.prod
    env_file:
      - .prod.env
    command: [ "gunicorn", "--bind", "0.0.0.0:5000", "manage:app" ]
    depends_on:
      - db
    expose:
      - 5000

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - apiv1

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.prod
    env_file:
      - .prod.env
    expose:
      - 5432
    volumes:
      - database-data-prod:/var/lib/postgresql/data/

volumes:
  database-data-prod:
    driver: local
