version: "3"
services:
  apiv1:
    build:
      context: ./apiv1
      dockerfile: Dockerfile
    env_file:
      - .dev.env
    command: [ "python", "manage.py", "run", "-h", "0.0.0.0" ]
    depends_on:
      - db
    volumes:
      - "./apiv1/.:/app"
    ports:
      - "5000:5000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - apiv1

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .dev.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
    driver: local
