insert into "Products" (id, name) values (1, 'Napkin Colour');
insert into "Products" (id, name) values (2, 'Apples - Spartan');
insert into "Products" (id, name) values (3, 'Oxtail - Cut');
insert into "Products" (id, name) values (4, 'Stock - Beef, Brown');
insert into "Products" (id, name) values (5, 'Aspic - Clear');
insert into "Products" (id, name) values (6, 'Nut - Pecan, Pieces');
insert into "Products" (id, name) values (7, 'Tart - Lemon');
insert into "Products" (id, name) values (8, 'Lettuce - Spring Mix');
insert into "Products" (id, name) values (9, 'Crab - Soft Shell');
insert into "Products" (id, name) values (10, 'Soup - Campbells - Chicken Noodle');
insert into "Products" (id, name) values (11, 'Wine - Lamancha Do Crianza');
insert into "Products" (id, name) values (12, 'Wine - Chateau Aqueria Tavel');
insert into "Products" (id, name) values (13, 'Mace Ground');
insert into "Products" (id, name) values (14, 'Lobster - Tail 6 Oz');
insert into "Products" (id, name) values (15, 'Pork - Suckling Pig');
insert into "Products" (id, name) values (16, 'Milk - 1%');
insert into "Products" (id, name) values (17, 'Beer - Labatt Blue');
insert into "Products" (id, name) values (18, 'The Pop Shoppe - Grape');
insert into "Products" (id, name) values (19, 'Longos - Lasagna Veg');
insert into "Products" (id, name) values (20, 'Olives - Black, Pitted');
insert into "Products" (id, name) values (21, 'Jagermeister');
insert into "Products" (id, name) values (22, 'Wine - Red, Cooking');
insert into "Products" (id, name) values (23, 'Split Peas - Green, Dry');
insert into "Products" (id, name) values (24, 'Crawfish');
insert into "Products" (id, name) values (25, 'Clams - Littleneck, Whole');
insert into "Products" (id, name) values (26, 'Wine - Casillero Del Diablo');
insert into "Products" (id, name) values (27, 'Beer - Alexander Kieths, Pale Ale');
insert into "Products" (id, name) values (28, 'Capon - Whole');
insert into "Products" (id, name) values (29, 'Nut - Macadamia');
insert into "Products" (id, name) values (30, 'Pork - Inside');
insert into "Products" (id, name) values (31, 'Carbonated Water - Blackcherry');
insert into "Products" (id, name) values (32, 'Chicken - Leg / Back Attach');
insert into "Products" (id, name) values (33, 'Carbonated Water - Lemon Lime');
insert into "Products" (id, name) values (34, 'Beef - Eye Of Round');
insert into "Products" (id, name) values (35, 'Soup - Canadian Pea, Dry Mix');
insert into "Products" (id, name) values (36, 'Steel Wool');
insert into "Products" (id, name) values (37, 'Mangostein');
insert into "Products" (id, name) values (38, 'Cleaner - Bleach');
insert into "Products" (id, name) values (39, 'Aromat Spice / Seasoning');
insert into "Products" (id, name) values (40, 'Artichokes - Jerusalem');
insert into "Products" (id, name) values (41, 'Chicken - Tenderloin');
insert into "Products" (id, name) values (42, 'Appetizer - Southwestern');
insert into "Products" (id, name) values (43, 'Truffle - Peelings');
insert into "Products" (id, name) values (44, 'Yogurt - Raspberry, 175 Gr');
insert into "Products" (id, name) values (45, 'Beer - Steamwhistle');
insert into "Products" (id, name) values (46, 'Pork - Back, Short Cut, Boneless');
insert into "Products" (id, name) values (47, 'Beef - Inside Round');
insert into "Products" (id, name) values (48, 'Wine - Ice Wine');
insert into "Products" (id, name) values (49, 'French Pastry - Mini Chocolate');
insert into "Products" (id, name) values (50, 'Peas Snow');
